config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  # resources :users
  # resource :session

  namespace :api, defaults: { format: :json } do
    resources :events, except: [:new, :edit]
    resources :users, except: [:new, :edit]
    resource :session, only: [:show, :create, :destroy]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  nickname        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  city_id         :integer          not null
#  host            :boolean          default(FALSE), not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :nickname, presence: true
  validates :city_id, presence: true
  validates :host, inclusion: { in: [true, false] }

  attr_reader :password
  after_initialize :ensure_session_token

  belongs_to :city
  has_many :hosted_events,
    class_name: "Event",
    foreign_key: :host_id,
    primary_key: :id,
    inverse_of: :event_host

  def self.find_by_credentials(user_params)
    user = User.find_by(email: user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  protected

    def ensure_session_token
      self.session_token ||= generate_session_token
    end

    def generate_session_token
      SecureRandom.urlsafe_base64(16)
    end

end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController
  
    def index
      @users = User.where({ host: true });
      render :index
    end

    def show
      @user = User.find(params[:id])
      render :show
    end

    def create
      @user = User.new(user_params)

      if @user.save
        sign_in!(@user)
        render :show
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity
      end
    end

    def update
      @user = User.update(user_params)

      if @user.save
        render :show
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      render json: {}
    end

    protected

      def user_params
        self.params.require(:user).permit(:email, :nickname, :city_id, :password)
      end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signed_in!, only: [:edit, :update, :destroy]
  before_action :verify_owner, only: [:edit, :update, :destroy]

  def new
    @user = User.new
    @cities = City.all
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end

  def edit
    @user = User.find(params[:id])
    @cities = City.all
    render :edit
  end

  def update
    @user = User.update(user_params)
    if @user.save
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :nickname, :city_id, :password)
    end

    def verify_owner
      user = User.find(params[:id])
      unless current_user == user
        redirect_to :forbidden
      end
    end
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update user": "Create user") %>

<form action="<%= action %>" method="post">
  <input name="_method" type="hidden" value="<%= method %>">
  <%= auth_token %>
  
  <label for="user_email">Email</label><br>
  <input name="user[email]" id="user_email" type="text"><br><br>
  
  <label for="user_nickname">Nickname</label><br>
  <input name="user[nickname]" id="user_nickname" type="text"><br><br>

  <label for="user_password">Password</label><br>
  <input name="user[password]" id="user_password" type="password"><br><br>

  <label for="user_city">City</label><br>
  <select name="user[city_id]" id="user_city">
    <% cities.each do |city| %>
      <option value="<%= city.id %>" <%= "selected" if (city.id == user.city_id) %>>
        <%= city.name %>
      </option>
    <% end %>
  </select><br><br>
  
  <input type="submit" value="<%= message %>"><br>
</form>

app/views/users/edit.html.erb
<h1>Edit info</h1>

<%= render "form", user: @user, cities: @cities %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user, cities: @cities %>